In [17]:
import tools
from tools import get_path,in_out_imformation,get_station_imfo
import pandas as pd
if __name__ == "__main__":
    name_list = get_path()
    stations_imfo = get_station_imfo()
    all_in_out = in_out_imformation(name_list,stations_imfo)
    station_in_out = pd.concat(all_in_out)
    station_in_out

In [30]:
station_in_out1= station_in_out.sort_values(by="日期")

In [34]:
station_in_out2 = station_in_out1.groupby("站名")[['入站','出站']]

In [35]:
df2=station_in_out2.aggregate([("最多人數","max"),('最少人數',"min"),('中間值','median')])
df2

       入站                 出站
     最多人數 最少人數     中間值  最多人數 最少人數     中間值
站名
七堵   7704  141  5706.0  8288  210  5745.0
三坑   1715   34  1298.0  1835   31  1333.5
三塊厝   933   16   464.0  1013   15   488.5
三姓橋  2125    3  1043.0  1603   16   980.5
三民     52    0     6.0    57    0    10.0
..    ...  ...     ...   ...  ...     ...
鼓山   2352    9   231.5  1055   16   240.0
龍井   2131   36   331.0  5506   35   318.0
龍泉    103    0    12.0   390    1    14.0
龍港    106    2    16.0   130    2    21.0
龜山    389    3    79.0   287    0    76.0

[241 rows x 6 columns]

In [44]:
serial=df2.stack(level=[0,1])
serial

C:\Users\Administrator\AppData\Local\Temp\ipykernel_8136\1887670631.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  serial=df2.stack(level=[0,1])

站名
七堵  入站  最多人數    7704.0
        最少人數     141.0
        中間值     5706.0
    出站  最多人數    8288.0
        最少人數     210.0
                 ...
龜山  入站  最少人數       3.0
        中間值       79.0
    出站  最多人數     287.0
        最少人數       0.0
        中間值       76.0
Length: 1446, dtype: float64

In [48]:
serial.index.names= ['站名','統計','出入站']
serial.unstack(level='站名')

站名           七堵      三坑     三塊厝     三姓橋    三民      三義     三貂嶺     上員       中壢  \
統計 出入站
入站 最多人數  7704.0  1715.0   933.0  2125.0  52.0  1697.0   989.0  245.0  42088.0
   最少人數   141.0    34.0    16.0     3.0   0.0    51.0     0.0    1.0    429.0
   中間值   5706.0  1298.0   464.0  1043.0   6.0   656.0    85.0   48.0  22034.0
出站 最多人數  8288.0  1835.0  1013.0  1603.0  57.0  1652.0  1171.0  175.0  43833.0
   最少人數   210.0    31.0    15.0    16.0   0.0    32.0     0.0    2.0    881.0
   中間值   5745.0  1333.5   488.5   980.5  10.0   669.0   103.0   54.0  22425.5

站名           中洲  ...      鳳山      鳳林       鶯歌      鹿野     麟洛      鼓山      龍井  \
統計 出入站           ...
入站 最多人數   934.0  ...  9590.0  1260.0  15908.0   803.0  401.0  2352.0  2131.0
   最少人數    11.0  ...   483.0    35.0    132.0    17.0    6.0     9.0    36.0
   中間值    359.0  ...  4531.5   326.0   8000.0   186.0  142.0   231.5   331.0
出站 最多人數  1445.0  ...  9018.0  1182.0  15773.0  1127.0  473.0  1055.0  5506.0
   最少人數    11.0  ...   489.0    42.0    125.0    18.0    4.0    16.0    35.0
   中間值    358.0  ...  4394.5   318.0   8042.5   172.0  154.0   240.0   318.0

站名          龍泉     龍港     龜山
統計 出入站
入站 最多人數  103.0  106.0  389.0
   最少人數    0.0    2.0    3.0
   中間值    12.0   16.0   79.0
出站 最多人數  390.0  130.0  287.0
   最少人數    1.0    2.0    0.0
   中間值    14.0   21.0   76.0

[6 rows x 241 columns]